# Upon each push, if anything under workflow or tests is changed, we would like to:
#
# 1) Install Snakemake via conda
# 2) Re-generate the DAG
# 3) Test the workflow with --use-conda
#

name: Run integration test on Ubuntu

on:
  push:
    branches: [ master ]
    paths: ['tests/integration/**', 'workflow/**', '.github/workflows/**']

jobs:
  auto_test:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -eo pipefail -l {0} # Needed for conda

    steps:

    - uses: actions/checkout@main

    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        use-mamba: false
        conda-solver: libmamba
        channels: conda-forge,bioconda
        channel-priority: strict

    - name: Install latest Snakemake and confirm version
      run: |
        conda config --remove channels defaults || true
        conda config --env --remove channels defaults || true
        conda install snakemake
        echo ---
        which snakemake
        snakemake --version

    - name: Run the workflow on toy data
      run: |
        test ! -e results
        snakemake --use-conda -j1 --configfile tests/integration.yaml
        ls results/*.pod5

    # If we generate the DAG now it should match the one in the repo,
    # except for issue https://github.com/snakemake/snakemake/issues/1709
    - name: Export the DAG as dag.dot
      run: |
        snakemake --configfile tests/integration.yaml --dag > dag.dot
        sed -i -e 's/,dashed//' dag.dot
        #diff -s dag.dot workflow/dag.dot
        [[ "$(wc <dag.dot)" == "$(wc <workflow/dag.dot)" ]]

